grails:
  profile: rest-api
  codegen:
    defaultPackage: ticketing
spring:
  application:
    name: ticketing-catalog
dataSource:
  url: ${JDBC_URL:jdbc:mysql://localhost:3306/ticketing}
  username: ${DB_USER:ticketing}
  password: ${DB_PASSWORD}
  driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8080
