plugins {
    id 'groovy'
    id 'org.apache.grails.gradle.grails-web' version '7.0.2'
}
group = 'ticketing'
version = '0.1.0'
repositories { mavenCentral(); maven { url = 'https://repo.grails.org/grails/core' } }
dependencies {
    implementation 'org.apache.grails:grails-core'
    implementation 'org.apache.grails:grails-web-boot'
    implementation 'org.apache.grails:grails-rest-transforms'
    implementation 'org.apache.grails:grails-controllers'
    implementation 'org.apache.grails:grails-interceptors'
    implementation 'org.apache.grails:grails-databinding'
    implementation 'org.apache.grails:grails-services'
    implementation 'org.apache.grails:grails-url-mappings'
    implementation 'org.springframework.boot:spring-boot-starter-tomcat'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    runtimeOnly 'com.mysql:mysql-connector-j'
    runtimeOnly 'org.fusesource.jansi:jansi'
}
java { toolchain { languageVersion = JavaLanguageVersion.of(17) } }
